SELECT F.*, group_concat(FG.GENRE_ID separator ',') AS GENRE
FROM FILMS F
JOIN FILM_GENRE FG ON F.ID = FG.FILM_ID WHERE id = 2
group by F.ID;

SELECT U.*, group_concat(S.SUBSCRIBER separator ',') AS SUBCRIBERS
FROM USERS U
JOIN SUBSCRIBES S ON U.ID = S.AUTHOR WHERE U.ID = 2
GROUP BY U.ID;

SELECT U.*,
       group_concat(S.SUBSCRIBER separator ',') AS SUBCRIBERS
FROM USERS U
LEFT JOIN SUBSCRIBES S ON U.ID = S.AUTHOR
WHERE U.ID = 1
GROUP BY U.ID;

SELECT F.*, group_concat(FG.GENRE_ID separator ',') AS GENRE
FROM FILMS F
LEFT JOIN FILM_GENRE FG ON F.ID = FG.FILM_ID
WHERE id = 5
GROUP BY F.ID;

SELECT F.*, group_concat(FG.GENRE_ID separator ',') AS GENRE
FROM FILMS F
         LEFT JOIN FILM_GENRE FG ON F.ID = FG.FILM_ID
WHERE id = 1
GROUP BY F.ID;

UPDATE FILMS
SET RATE=RATE+5
WHERE id = 1;

MERGE INTO FILM_GENRE (FILM_ID, GENRE_ID) VALUES (2, 1);