-- INSERT INTO PUBLIC.USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES ('tom@yandex.ru', 'tom', 'Thomas Anderson', '1989-03-28');
-- INSERT INTO PUBLIC.USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES ('jerry@yandex.ru', 'jerry', 'Jerry Lee', '1966-12-08');
-- INSERT INTO PUBLIC.USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES ('spike@yandex.ru', 'spike', 'Spike Jones', '1923-11-22');

INSERT INTO PUBLIC.GENRE (NAME) VALUES ('Комедия');
INSERT INTO PUBLIC.GENRE (NAME) VALUES ('drama');
INSERT INTO PUBLIC.GENRE (NAME) VALUES ('cartoon');
INSERT INTO PUBLIC.GENRE (NAME) VALUES ('thriller');
INSERT INTO PUBLIC.GENRE (NAME) VALUES ('documentary');
INSERT INTO PUBLIC.GENRE (NAME) VALUES ('action');
INSERT INTO PUBLIC.MPA (NAME) VALUES ('G');
INSERT INTO PUBLIC.MPA (NAME) VALUES ('PG');
INSERT INTO PUBLIC.MPA (NAME) VALUES ('PG-13');
INSERT INTO PUBLIC.MPA (NAME) VALUES ('R');
INSERT INTO PUBLIC.MPA (NAME) VALUES ('NC-17');


-- INSERT INTO PUBLIC.FILMS (NAME, RATING, DESCRIPTION, RELEASE_DATE, DURATION) VALUES ('Терминатор', 1, 'Фильм про робота', '1989-03-28', 1000);
-- INSERT INTO PUBLIC.FILMS (NAME, RATING, DESCRIPTION, RELEASE_DATE, DURATION) VALUES ('Терминатор 2', 3, 'Хороший фильм про двух роботов', '1992-03-28', 1200);
-- INSERT INTO PUBLIC.FILMS (NAME, RATING, DESCRIPTION, RELEASE_DATE, DURATION) VALUES ('Терминатор 3', 5, 'Плохой фильм про двух роботов', '2003-03-28', 1100);


-- INSERT INTO PUBLIC.FILM_GENRE (FILM_ID, GENRE_ID) VALUES (1, 4);
-- INSERT INTO PUBLIC.FILM_GENRE (FILM_ID, GENRE_ID) VALUES (1, 2);
-- INSERT INTO PUBLIC.FILM_GENRE (FILM_ID, GENRE_ID) VALUES (2, 6);
-- INSERT INTO PUBLIC.FILM_GENRE (FILM_ID, GENRE_ID) VALUES (2, 2);
-- INSERT INTO PUBLIC.FILM_GENRE (FILM_ID, GENRE_ID) VALUES (2, 4);
-- INSERT INTO PUBLIC.FILM_GENRE (FILM_ID, GENRE_ID) VALUES (3, 1);